# Generated by Django 4.1.2 on 2022-11-01 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_blog', '0002_alter_bloguser_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='auth_id',
            field=models.ForeignKey(db_column='auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='AUTH_ID'),
        ),
    ]
