# Generated by Django 4.1.2 on 2022-11-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0005_alter_bloguser_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bloguser',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user_blog.categories'),
            preserve_default=False,
        ),
    ]
