# Generated by Django 4.1.2 on 2022-11-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0006_categories_bloguser_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
