# Generated by Django 4.1.2 on 2022-11-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0007_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
